name: Deploy to private server

on:
  push:
    branches: ["master"]
    tags:
      - "*"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: build docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: derposbot:latest
